issue54
ytskmt14/step-up-camp-lp pull request #55
Opened 2021-07-04 11:57 UTC by kngmed

デザイン修正しました、
変なところあると思いますので、
あったら指摘ください

2021-07-07 14:25 UTC, ytskmt14 requested changes

2021-07-07 14:25 UTC, ytskmt14 commented on src/components/Footer.vue
> +      text-align: center;
vuetifyでクラスが提供されてるからそっちの方がいいかも。

https://vuetifyjs.com/ja/styles/text-and-typography/#text

```html
<v-footer
    dark
    padless
    class="mt-4 text-center"
    style="
    ・・・
```

2021-07-07 14:25 UTC, ytskmt14 commented on src/components/Footer.vue
> +      style="margin: 0 auto"
たぶんスタイルまとめれる
https://vuetifyjs.com/ja/styles/spacing/

```html
<div
    class="title font-weight-light grey--text text--lighten-1 text-center mx-auto my-0"
```

2021-07-07 14:25 UTC, ytskmt14 commented on src/pages/About.vue
> +      <p style="text-align: center">
これもtext-centerにしたい

2021-07-07 14:25 UTC, ytskmt14 commented on src/pages/About.vue
> +      <v-timeline style="max-width: 860px; margin: 0 auto">
`margin: 0 auto`をclass定義に変えたい

`mx-auto my-0`でいけるはず

2021-07-07 14:25 UTC, ytskmt14 commented on src/pages/Contact.vue
> +      <div style="margin: 0 auto; max-width: 800px; text-align: center">
vuetifyのclass使いたい。
こんなイメージ
```html
<div class="mx-auto my-0 text-center" style="...">
```

2021-07-07 14:25 UTC, ytskmt14 commented on src/pages/Contact.vue
> +  methods: {},
使わないなら消しときたい

2021-07-10 08:46 UTC, ytskmt14 approved these changes

2021-07-10 08:46 UTC, merged

2021-11-20 04:26 UTC, kngmed commented
```diff
diff --git a/src/assets/top-img.png b/src/assets/top-img.png
index 8014869..38245ca 100644
Binary files a/src/assets/top-img.png and b/src/assets/top-img.png differ

```